version: 2
jobs:
  build:
    machine: true
    working_directory: ~/workdir
    steps:
      - checkout
      - run:
          name: Compile
          command: ./build.sh "${CIRCLE_PROJECT_REPONAME}:1.0.${CIRCLE_BUILD_NUM}"
      - run:
          name: Run and return 0
          command: docker run "${CIRCLE_PROJECT_REPONAME}:1.0.${CIRCLE_BUILD_NUM}"
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker tag "${CIRCLE_PROJECT_REPONAME}:1.0.${CIRCLE_BUILD_NUM}" "${CIRCLE_PROJECT_REPONAME}:latest"
              docker push "${CIRCLE_PROJECT_REPONAME}:1.0.${CIRCLE_BUILD_NUM}"
              docker push "${CIRCLE_PROJECT_REPONAME}:latest"
            fi
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build